            - 名称：下载构建工件
  用途：actions/download-artifact@v4.1.8
  和：
    # 要下载的工件的名称。如果未指定，则下载运行的所有工件。
    名称：#可选
    # 目标路径。支持基本波浪符号扩展。默认为 $GITHUB_WORKSPACE
    路径：#可选
    # 与应下载的工件匹配的 glob 模式。如果指定了名称，则忽略。
    模式：#可选
    # 当多个工件匹配时，这会改变目标目录的行为。如果为 true，则下载的工件将位于路径指定的同一目录中。如果为 false，则下载的工件将被提取到指定路径内的单独命名目录中。
    合并多个：#可选，默认为 false
    # 用于通过 GitHub API 进行身份验证的 GitHub 令牌。从其他存储库或从其他工作流程运行下载工件时需要此令牌。如果未指定，则操作将尝试从当前存储库和当前工作流程运行下载工件。
    github-token: # 可选
    # 仓库所有者和仓库名称以“/”连接在一起。如果指定了 github-token，则这是将从中下载工件的仓库。
    存储库：# 可选，默认为 ${{ github.repository }}
    # 上传所需下载工件的工作流运行的 ID。如果指定了 github-token，则这是从中下载工件的运行。
    run-id: # 可选，默认为 ${{ github.run_id }}
          
